### ISSUE TITLE
`ReverseDiff` limitations and issues 

### ISSUE THREAD

**Issue by yebai** [chalk-lab/Mooncake.jl#25]
Let's try to address these limitations and issues in this new AD implementation:  

- https://github.com/TuringLang/Turing.jl/issues/1754#issuecomment-1772851160
- https://github.com/JuliaDiff/ReverseDiff.jl/issues/234

**Comment by willtebbutt** [comment]
I've gone through https://github.com/TuringLang/Turing.jl/issues/1754#issuecomment-1772851160 , and either
1. they're not a problem for us, or
2. we don't support differentiating them (e.g. nested differentiation)
